### PR TITLE
#255 handle dangling pipes

### PR DESCRIPTION
**Pull request by jk1**

### CODE REVIEW

**Comment by robinst** [comment]
Hey, thanks for looking into this. Looking at what GitHub does (which we're trying to mirror with the extension), it renders this:

```
Abc|Def
---|---
1|2
|
```

Like this:

Abc|Def
---|---
1|2
|

---

See how `|` is not actually part of the table anymore? Can you come up with a fix that handles it the same way?

**Comment by robinst** [comment]
Hey @jk1 just checking in, have you seen my comment?

**Comment by robinst** [comment]
Looked at it myself, the fix is a bit more involved, will raise a PR soon.

**Comment by robinst** [comment]
PR: https://github.com/commonmark/commonmark-java/pull/268

**Comment by jk1** [comment]
Hi @robinst thank you for the followup. I have seen the your comment back then, but didn't manage to implement what's requested. Things got wild really fast and was forced to flee my home country. Thanks a ton for getting back to this and providing a proper fix.

**Comment by robinst** [comment]
Hey! I'm so sorry to hear that, I can't imagine what that must be like. Hope things are looking better now.

**Pull request closed without merging**
